"""Gemini API client for AI text detection validation."""
import os
from typing import Dict, Optional

import google.generativeai as genai


class GeminiDetector:
    """Client for using Google Gemini API to validate AI text detection."""

    def __init__(self, api_key: Optional[str] = None):
        """Initialize Gemini client.

        Args:
            api_key: Gemini API key. If None, reads from GEMINI_API_KEY env var.
        """
        self.api_key = api_key or os.getenv('GEMINI_API_KEY')

        if not self.api_key:
            raise ValueError(
                "Gemini API key not found. "
                "Set GEMINI_API_KEY environment variable or pass api_key parameter."
            )

        # Configure Gemini
        genai.configure(api_key=self.api_key)

        # Use Gemini 2.5 Flash for fast, cost-effective inference
        self.model = genai.GenerativeModel('gemini-2.5-flash')

    def analyze_text(self, text: str) -> Dict:
        """Analyze text to determine if AI-generated.

        Args:
            text: Text to analyze

        Returns:
            Dict with keys:
                - label: 'Human', 'AI', or 'Inconclusive'
                - confidence: float 0-1
                - reasoning: str explanation
        """
        prompt = f"""Analyze the following text and determine if it was written by a human or generated by AI.

Text to analyze:
\"\"\"{text}\"\"\"

Provide your analysis in the following format:
CLASSIFICATION: [Human/AI/Inconclusive]
CONFIDENCE: [0.0-1.0]
REASONING: [Brief explanation]

Focus on patterns like:
- Writing style and naturalness
- Vocabulary diversity and word choice
- Sentence structure variability
- Presence of filler words or natural imperfections
- Logical flow and coherence
- Use of clichés or generic phrasing common in AI text
"""

        try:
            response = self.model.generate_content(prompt)
            result_text = response.text

            # Parse the response
            lines = result_text.strip().split('\n')

            classification = 'Inconclusive'
            confidence = 0.5
            reasoning = 'Unable to determine'

            for line in lines:
                line = line.strip()
                if line.startswith('CLASSIFICATION:'):
                    classification = line.split(':', 1)[1].strip()
                elif line.startswith('CONFIDENCE:'):
                    try:
                        confidence = float(line.split(':', 1)[1].strip())
                    except ValueError:
                        confidence = 0.5
                elif line.startswith('REASONING:'):
                    reasoning = line.split(':', 1)[1].strip()

            # Normalize classification to match our system
            if 'human' in classification.lower():
                classification = 'Human'
            elif 'ai' in classification.lower():
                classification = 'AI'
            else:
                classification = 'Inconclusive'

            return {
                'label': classification,
                'confidence': confidence,
                'reasoning': reasoning
            }

        except Exception as e:
            print(f"Gemini API error: {e}")
            return {
                'label': 'Inconclusive',
                'confidence': 0.0,
                'reasoning': f'Gemini API error: {str(e)}'
            }
